# Generated by Django 3.2 on 2022-04-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('submitted_at', models.DateField(auto_now_add=True, verbose_name='ثبت شده در')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_details', to='core.userprofile', verbose_name='پروفایل کاربر')),
            ],
        ),
    ]
