# Generated by Django 4.0.3 on 2022-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_question_quiz_userprofile_confirmedanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedanswer',
            name='question_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='confirmedanswer',
            unique_together={('user_profile', 'question_id')},
        ),
    ]
