# Generated by Django 4.0.3 on 2022-03-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_confirmedanswer_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedanswer',
            name='answer_id',
            field=models.IntegerField(),
        ),
    ]
