# Generated by Django 4.0.3 on 2022-03-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_confirmedanswer_answer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmedanswer',
            name='correct_answer',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
