# Generated by Django 4.0.3 on 2022-04-02 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_confirmedanswer_correct_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Group',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='confirmedanswer',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_answers', to='core.userprofile'),
        ),
    ]
