# Generated by Django 4.0.3 on 2022-04-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_quiz_group_rename_quiz_question_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='national_code',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
