# Generated by Django 4.0.3 on 2022-04-04 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_national_code_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='national_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
    ]
