# Generated by Django 4.0.3 on 2022-04-04 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_remove_userprofile_national_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'پاسخ', 'verbose_name_plural': 'پاسخ ها'},
        ),
        migrations.AlterModelOptions(
            name='confirmedanswer',
            options={'verbose_name': 'پاسخ ثبت شده', 'verbose_name_plural': 'پاسخ های ثبت شده'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'گروه', 'verbose_name_plural': 'گروه ها'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'پروفایل کابر', 'verbose_name_plural': 'پروفایل های کاربران'},
        ),
        migrations.RemoveField(
            model_name='confirmedanswer',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='confirmedanswer',
            name='is_correct_answer',
            field=models.BooleanField(blank=True, default=1, help_text='آیا پاسخ داده شده صحیح است؟', verbose_name='پاسخ صحیح؟'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='پاسخ صحیح'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question', verbose_name='سوال'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=250, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='confirmedanswer',
            name='answer_id',
            field=models.IntegerField(verbose_name='آیدی پاسخ'),
        ),
        migrations.AlterField(
            model_name='confirmedanswer',
            name='question_id',
            field=models.IntegerField(blank=True, verbose_name='آیدی سوال'),
        ),
        migrations.AlterField(
            model_name='confirmedanswer',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_answers', to='core.userprofile', verbose_name='پروفایل کاربر'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='question',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='core.group', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=250, verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
