# Generated by Django 4.0.3 on 2022-04-06 14:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_confirmedanswer_submittedanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedanswer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submittedanswer',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_answers', to='core.userprofile', verbose_name='پروفایل کاربر'),
        ),
    ]
