# Generated by Django 4.0.3 on 2022-04-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_submittedanswer_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedanswer',
            name='submitted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
