# Generated by Django 4.0.3 on 2022-04-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_submittedanswer_submitted_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submittedanswer',
            unique_together={('user_profile', 'question_id', 'submitted_at')},
        ),
    ]
